### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by mbrakhane** [SEMO-GABD/public_discussion#1]
Was anyone having trouble with all three files to show up in the 'commit' window? How did you fix it?

**Comment by mtaylor-semo** [comment]
What assignment are you? Which three files are you talking about? Only files that have changed should show up in the commit window.

**Comment by mbrakhane** [comment]
Assignment 1. The example showed all three files (README, gitignore, and .rproj) in the commit window so I thought all of them needed to go there as well. Sorry, nevermind.

**Comment by mtaylor-semo** [comment]
I see. The example was from me working in real time so it showed some files that might not apply in your situation. I'll update the assignment.
