### ISSUE TITLE
HW 07 Limpets

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#10]
Dr. Taylor,

I can't get this to work.  I couldn't even get the file path to work with ../data, so I inserted the entire path. 

 ---
title: "HW 07: Data Importing and Wrangling 1"
author: "Ryan McAnulty"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
file_path <- "C:\\Users\\mcanu\\Desktop\\BI485\\mcanulty_ryan\\data"
```

```{r}
limpets_data <- read_csv(file.path(file_path, "limpets.csv"), col_types = "ncc")
```

```{r}
limpets_data$Site <- factor(limpets_data$Site, levels = c("PBL", "KNRM", "VBG", "WP", "PF", "DP", "SIO", "CTZ1", "CTZ2", "CNM"), ordered = TRUE)
```

```{r}
ggplot(data = limpets_data) +
  geom_boxplot(mapping = aes(x = Length, y = Site, color = Protected), labs(x = "Length (mm)"))
```
Is any of this close?

Thanks,
Ryan

**Comment by mtaylor-semo** [comment]
Yes, it's spot on. So, your direct path worked to access your files? The file path issue seems to be a deeper problem associated with platform differences.

**Comment by RyanDMcAnulty** [comment]
Yes, the direct path worked.  With ../data, it kept looking in the ..\..\hw07 not the ..\..\data folder.

**Comment by mtaylor-semo** [comment]
The two dots `..` in `../data` tells DOS to back up one directory in the hierarchy. In other words, it should move to the same folder as your project file, where it would then find the data folder.

What version of Windows are you using?


Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by mtaylor-semo** [comment]
Do me a favor: With your HW07.Rmd file open, click and hold the small down arrow on the `Knit` button, then choose `Knit Directory`. Please tell me whether the check mark is next to Document Directory, Project Directory, or Current Working Directory.  Thanks.

**Comment by mtaylor-semo** [comment]
I think I have figured out the best solution for importing. Would you be willing to test an idea for me? If so, here are the steps to test on the limpets data.

First, install the `here` package, either from the menu or `install.packages("here")`.

I am assuming the `limpets.csv` file is still in your `data` folder at the same level as your Rproj file.

Next, include `library(here)` in the same chunk as `library(tidyverse)` and run that chunk.

```
library(tidyverse)
library(here)
```

Skip your chunk that sets the `file_path` variable.  We're going to get rid of it, assuming this works.
```
# skip this
file_path <- THE_PATH_THAT_DOESNT_ALWAYS_WORK.
```

Then, replace your `read_csv` code that has file.path and file_path, etc. with this line. Run the chunk. Does it work?

`limpets_data <- read_csv(here("data", "limpets.csv"), col_types = "ncc")`

**Comment by mtaylor-semo** [comment]
PS: Don't worry about the Knit button question. The `here` solution is what I want to use going forward so I am interested in the result of that test.

**Comment by RyanDMcAnulty** [comment]
Yes, the here package worked.

**Comment by mtaylor-semo** [comment]
Thank you!

**Comment by RyanDMcAnulty** [comment]
Yes sir!  Thank you!

**Comment by williamzoughaib** [comment]
Following the above steps, it worked for me as well.  Thanks for posting the issue Ryan.

**Comment by mtaylor-semo** [comment]
Thanks for testing, Willam!

**Comment by mtaylor-semo** [comment]
Solution posted in [Issue 11](https://github.com/SEMO-GABD/public_discussion/issues/11).
