### ISSUE TITLE
HW 07 Blacklips Chunk #4

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#13]
```{r}
abalone_cleaned[abalone_cleaned$Height == 0, "Height"] 
na_if(abalone_cleaned$Height, 0)
drop_na(abalone_cleaned)
ggplot(data=abalone_cleaned) +
  geom_point(mapping = aes(x = Height, y = Rings, color = Type))
```
I  cannot get the 0 points to set to NA and then not plot on the graph.  This is the only hold up for turning this in.  HELP!!

**Comment by mtaylor-semo** [comment]
Of all that code, the only thing I think you have to do is

```
na_if(abalone_cleaned$Height, 0)
```

The problem seems to be that you are not saving the result. `na_if` converts your zeros to `NA`. You appear to have that set correctly. But, where are you saving the results?

**Comment by RyanDMcAnulty** [comment]
```{r}
abalone_no_outliers <- na_if(abalone_cleaned$Height, 0)
ggplot(data=abalone_no_outliers) +
    geom_point(mapping = aes(x = Height, y = Rings, color = Type))
```

Gives this error:
Error: `data` must be a data frame, or other object coercible by `fortify()`, not a numeric vector

**Comment by RyanDMcAnulty** [comment]
Never mind.  I got it to work.

Thanks!
