### ISSUE TITLE
Running the ifelse function

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#15]
ifelse (mass >= 0,   # Test: TRUE or FALSE
      mass <- mass,    # If test is true, keep mass as is
      mass == 0)       # If test is false, set mass to 0
  ifelse (tarsus >= 0, # Same test on tarsus length  
      tarsus <- tarsus,
      tarsus == 0)
  ifelse (slope >= 0,  # Same test on slope value  
      slope <- slope, 
      slope == 0)

Is there a way to trim this down with pipes or is it just wrong anyways? HA

**Comment by mtaylor-semo** [comment]
No use for pipes here. You're testing three different variables so your construct is fine except that `mass == 0` (the no part of your construct) is a logical test, not assigning the value 0 to mass. You need `mass <- 0`.

**Comment by RyanDMcAnulty** [comment]
Just to confirm, like this?
scaled_mass <- function(mass = FALSE, tarsus = FALSE, slope = FALSE) {
  ifelse (mass >= 0,   # Test: TRUE or FALSE
      mass <- mass,    # If test is true, keep mass as is
      mass <-0)       # If test is false, set mass to 0
  ifelse (tarsus >= 0, # Same test on tarsus length  
      tarsus <- tarsus,
      tarsus <-0)
  ifelse (slope >= 0,  # Same test on slope value  
      slope <- slope, 
      slope <-0)
  mass * (((mean(tarsus)) / tarsus) ^ slope)
}

**Comment by mtaylor-semo** [comment]
OK, with context I see what you are trying to do. Instead of setting the arguments to FALSE inside of `function()`, why not just set them to zero? Like this,

```
scaled_mass <- function(mass = 0, tarsus = 0, slope = 0) { Code to do the calculation}
```
If you call `scaled_mass(mass = df$my_mass, ...)` then mass will automatically be overridden by the data you pass to the function.

**Comment by RyanDMcAnulty** [comment]
In that case, this gives the correct answer, but is this sound? Just these two lines?

scaled_mass <- function(mass = 0, tarsus = 0, slope = 0) {
  mass * (((mean(tarsus)) / tarsus) ^ slope) # This does the calculations for the scaled_mass
}

**Comment by mtaylor-semo** [comment]
That's all you need. It is sound. Well done.

**Comment by RyanDMcAnulty** [comment]
Thank you!
