### ISSUE TITLE
HW 11

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#17]
I'm a little confused as to exactly what you want for the homework.

From the describe the results, forward.  Do we pick variables that we think will make interesting case studies, or are we still explaining the outliers here. Or are we done with outliers after Explore the data.  Also, should we remove the outlier.

Thank you!

**Comment by mtaylor-semo** [comment]
The previous assignment showed you several ways of plotting data to look for outliers. You saw in some cases data points that looked like outliers but in reality were (probably) not. In other cases, the points were actual outliers.  I want you to apply those techniques to identify those you think are actual outliers.  Use graphs that support your conclusions. 

You do not have to remove outliers.

After that, choose any four variables that you think will make suitable Cleveland plots and plot them in a 2 x 2 grid. Then, choose three *different* variables to produce the histogram and density plots.

The overall idea is to explore the *Aegla* data using the ideas from the Zuur et al. paper.  What if you had collected these data yourself? You would need to look for outliers, make histograms, etc.

Does this help?

**Comment by RyanDMcAnulty** [comment]
Yes, thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
