### ISSUE TITLE
HW12

### ISSUE THREAD

**Issue by williamzoughaib** [SEMO-GABD/public_discussion#18]
In regards to the POSIXct format, are we making up a time of day or are we just using the mdy() or similar functions.  

As of right now, I have been making up times to work with the ymd_hms() function.  Below is an example
```{r}
birth_time <- ymd_hms("1998-05-14 11:11:11")
birth_time
```

**Comment by mtaylor-semo** [comment]
Just mdy() etc. No need for times. Follow the examples for the women scientists and MLK.


Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by williamzoughaib** [comment]
I am having issues trying to remove NAs from the data when importing the file.    
```{r}
lake_data <- read_csv(here("data","lake_ice.csv")) 
lake_data
```

I could do this, but -999 still shows up.  
```{r}
lake_data <- read_csv(here("data","lake_ice.csv")) %>% 
  drop_na()
lake_data
```


I tried googling, but i cannot find anything relevant to dropping -999 values.

**Comment by mtaylor-semo** [comment]
`drop_na()` drops NAs, but so far R has no reason to think that `-999 == NA`. Google is not always your friend. On the other hand, `?read_csv` is helpful. One of the arguments to `read_csv` is `na = `.  You tell it was values to recognize as `NA`.  *Always* remember to try `?function` for details.

**Comment by williamzoughaib** [comment]
Thanks.  I got it.  I had tried NA, but i may have forgotten the ""

**Comment by williamzoughaib** [comment]
```{r}
ggplot(data=sum_river_data)+
  geom_line(mapping=aes(x=Month,y=mean_discharge),size=0.3,color="grey70")
```

How do I get Year input into the geom_line()?  I believe I followed the first two bullet points.

**Comment by williamzoughaib** [comment]
Never mind.  Got it.
