### ISSUE TITLE
HW 13

### ISSUE THREAD

**Issue by aerussom** [SEMO-GABD/public_discussion#19]
Having difficulty writing the regex search string for the caat_seq variable.  This is what I have been trying to manipulate, but no luck...
caat_seq <- {"^CCAAT", "ATG$"}

**Comment by mtaylor-semo** [comment]
The `^CCAAT` tells regex to look for that sequence at the *start* of the text line but the sequence could easily begin (and does) begin somewhere in the middle of the sequence.  Likewise, `$` is the last character of a line but there's no reason to suspect that `ATG` is the final sequence of a line.  In other words, you sequence is looking for:

`CCAAT..............<some number of chars>.......ATG`

Next, I think you are trying to incorporate the `{start, stop}` which you must do. I suspect that you are thinking of `^` as the start and `$` as the stop.  That's not the case.  The start and stop refer to the minimum and maximum *distance* between the two search strings.  Thus, your clue from the exercise is:

- Make a regex search string called `caat_seq` that begins with "CCAAT", ends with "ATG"", and allows for a stretch of 100-150 nucleotides between the two.

**Comment by mtaylor-semo** [comment]
See the [Section 14.3.4 Repetition](https://r4ds.had.co.nz/strings.html#repetition) from the text.

**Comment by williamzoughaib** [comment]
I am extremely confused by this as well.

**Comment by RyanDMcAnulty** [comment]
Ditto.

**Comment by mtaylor-semo** [comment]
Consider the string `ABCDEFMSTGHIJKLMNOPQRBCDESTMSTUVWXYZ`. Assume we want to find a string that begins with `BCDE` and ends with `MST`.  There are two short strings and one long string that match the pattern. I've used spaces to highlight the matches.

#### Short strings
`A BCDEFMST GHIJKLMNOPQR BCDESTMST UVWXYZ`

#### Long string
`A BCDEFMSTGHIJKLMNOPQRBCDESTMST UVWXYZ`

The letters that separate `BCDE` from `MST` can be any letter. In RegEx, the `.` represents any character. So we can begin to think of a search string with the pattern `BCDE.+MST`.  This is `MST` is separated from `BCDE` by 1 or more characters. 

Say we know from other data that MST in our sequence of interest is at least 10 characters away from BCDE but no more than 25 characters. That means we would have to find the long string and neither of the two short strings. 

Therefore, we use {start,stop} along with `.` to modify our search sequence.  We want `BCDE.{10,25}MST`.  That gives as a RegEx pattern of BCDE followed by any string of characters (.) that is 10-25 characters long, followed by MST. 

Run this code in your R console.
```
# Starting sequence
my_seq <- "ABCDEFMSTGHIJKLMNOPQRBCDESTMSTUVWXYZ"

# Search string.  Notice the `.` after the E. The period (any character)
# is being matched 10-25 times.
search_seq <- "BCDE.{10,25}MST"

# Count number of times the matched string is found
str_count(my_seq, search_seq)

# Extract all instances, to show we're getting the right string.
str_extract_all(my_seq, search_seq)

# [[1]]
# [1] "BCDEFMSTGHIJKLMNOPQRBCDESTMST"
```
To demonstrate that it works, change the search sequence to find all instances where MST is separated from BCDE by only 1-10 characters, and run again.

```
# Search string
search_seq <- "BCDE.{1,10}MST"

# Count number of times the matched string is found
str_count(my_seq, search_seq)

# Extract all instances
str_extract_all(my_seq, search_seq)

# [[1]]
# [1] "BCDEFMST"  "BCDESTMST"
```
Both of the short strings were found, not the long one.

Now, some of you may have thought that you could just do `BCDE.+MST`. In the example above it would work but in the DNA exercise it would not. RegEx is greedy, meaning it would find the longest possible sequence that matches the pattern. Using `BCDE.+MST` for HW13 would return a string that is 3,224 characters long, which is nearly the entire sequence given to you. That would be incorrect.

With careful use of the {start,stop} pattern, you can control how you search for specific patterns in text.  

I'll work this example into the notes for future reference.

**Comment by williamzoughaib** [comment]
```{r}
ants_data %>% 
  pivot_longer(names_to="species",values_to="abundance",matches(regex("[:Upper:]...\\.[:lower:]",ignore_case = TRUE)))
```

I have tried this.  I still have all the species columns.  Where am I going wrong?  I do have the species column now

**Comment by RyanDMcAnulty** [comment]
caat_box <- "CCAAT"
tata_box <- "CTATAA"
str_count(DNA, caat_box)
str_count(DNA, tata_box)
caat_seq <- "caat_box.{100,150}ATG"
str_count(DNA,caat_seq)
tata_seq <- "tata_box.{50,100}ATG"
str_count(DNA,tata_seq)

both counts come back with 0.  Can't figure it out.

**Comment by aerussom** [comment]
I am also stuck there too William.  This is my code
ants_raw %>% 
  pivot_longer(names_to="species",values_to="abundance",matches("[:upper:]\\.[:lower:]"))

I can also have the new species column, but it didn't drop the individual species columns

**Comment by aerussom** [comment]
I got species names and values in my new species column with the following code
ants_raw %>% 
  pivot_longer(names_to="species",values_to="abundance",matches("[:upper:].+\\.[:lower:].+", ignore.case = FALSE))

**Comment by mtaylor-semo** [comment]
Please raise new issues for unrelated problems, even in the same assignment. It makes it easier to follow specific problems.

**Comment by mtaylor-semo** [comment]
```
caat_box <- "CCAAT"
tata_box <- "CTATAA"
str_count(DNA, caat_box)
str_count(DNA, tata_box)
caat_seq <- "caat_box.{100,150}ATG"
```
Ryan you define `caat_box` as a variable but when you try to use that variable in defining `caat_seq`, you include it in quote marks, making `caat_box` a literal string, not a variable. As a result, you are searching for a string called `caat_box` instead of `CCAAT`.
