### ISSUE TITLE
REGEX search

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#20]
•Make a regex search string calledcaat_seqthat begins with “CCAAT”, ends with “ATG”", and allowsfor a stretch of 100-150 nucleotides between the two.Hint:Remember{start, stop}.

I have searched the literature, the web, the cheatsheets, everywhere I can think of and I simply cannot figure out how to do this.

For what its worth, here is some code that I have used:

tata_seq <- str_locate_all(DNA,{"CCAAT", "ATG"})

Please, help.

**Comment by mtaylor-semo** [comment]
Answered in [Issue 19](https://github.com/SEMO-GABD/public_discussion/issues/19).
