### ISSUE TITLE
HW13 Pivoting on species columns 

### ISSUE THREAD

**Issue by mtaylor-semo** [SEMO-GABD/public_discussion#22]
Original question from William Z.

```{r}
ants_data %>% 
  pivot_longer(names_to="species",values_to="abundance",matches(regex("[:Upper:]...\\.[:lower:]",ignore_case = TRUE)))
```

I have tried this.  I still have all the species columns.  Where am I going wrong?  I do have the species column now.  

```{r}
ants_data %>% 
  pivot_longer(names_to="species",values_to="abundance",matches(regex("([A-Z]).+\\.(.+)$",ignore_case = FALSE)))
```

I just tried this as well.

_Originally posted by @williamzoughaib in https://github.com/SEMO-GABD/public_discussion/issues/19#issuecomment-667694866_

**Comment by williamzoughaib** [comment]
```{r}
ants_tidy <- ants_data %>% 
  pivot_longer(names_to="species",values_to="abundance",matches(regex("([[:upper:]]).+\\.(.+)$"),ignore.case = FALSE)) %>% 
  select(!(season:sample))
ants_tidy
```
This is what I ended with.

**Comment by mtaylor-semo** [comment]
This was closest. I reformatted the code to make it more legible.

```{r}
ants_data %>%
  pivot_longer(names_to = "species",
               values_to = "abundance",
               matches(regex("([A-Z]).+\\.(.+)$", ignore_case = FALSE)))
```

This captures `seas.code` as one of the species names, which you don't want. The initial problem stems from using `regex()`. You need to put the closing parenthesis on the right side of the right quote.  ([A-Z]).+\\.(.+)$` is the regex pattern so it should not include the `ignore_case` argument.  That will make it work, but you can simply this even further.

You don't need to use `regex()`. You also don't need to use the parentheses around `[A-Z]` or around the `.+`. Finally, don't use the `$`.

**Comment by mtaylor-semo** [comment]
Amanda's code shown in [this comment](https://github.com/SEMO-GABD/public_discussion/issues/19#issuecomment-667699190) is also an elegant solution.

**Comment by mtaylor-semo** [comment]
As it turns out, Amanda's code was *almost* correct.

```
ants_raw %>%
  pivot_longer(names_to = "species",
  values_to = "abundance",
  matches("[[:upper:]].+\.[[:lower:]].+", ignore.case = FALSE))
```
The only differences is that double brackets are needed, `[[ ]]` instead of single `[]`. I've never used the built-in character patterns like  `[[:upper:]]` so I learned something from this exercise. Thanks!
