### ISSUE TITLE
HW 13 - all species not being represented in new species column for ants data 

### ISSUE THREAD

**Issue by aerussom** [SEMO-GABD/public_discussion#23]
ants_data_wrangled <- ants_raw %>% 
  pivot_longer(names_to="species",values_to="abundance",matches("[:upper:].+\\.[:lower:].+", ignore.case = FALSE)) %>% 
  select("year", "species", "abundance")
ants_data_wrangled

Using this code, not all species are transferred to the new species column, only 4 are listed....

**Comment by mtaylor-semo** [comment]
For some reason, only four columns seem to match but I can't figure out why. If you don't pipe to `select()` you'll find most species columns are still present *except* for the four that do match. I can't figure out why only those four match. It seems they all should match. I'll have to play around to figure out what's going on. In the mean time, just use this string for the match string.
```
"[A-Z].+\\..+"
```
