### ISSUE TITLE
Capture pattern for species

### ISSUE THREAD

**Issue by williamzoughaib** [SEMO-GABD/public_discussion#24]
```{r}
ants_mut <- ants_tidy %>% mutate(species=str_replace(species,"([A-Z].{3}).+([a-z]{4})","\\1\\2")) 
ants_mut
```

How do i capture the pattern for the first four digits of the species.  I have genus.

**Comment by mtaylor-semo** [comment]
You are close: (^[A-Z][a-z]{0,3}).*\\.([a-z]{1,4}).*", "\\1\\2")

You're capturing the first capital letter followed by the next three characters but they you're capturing any number of characters (`.+`) followed by [a-z]{4}. However, the `.+` is greedy.  You're also specifying exactly four characters for the final pattern, but what if there were only two or three letters in the specific epithet?

**Comment by aerussom** [comment]
I absolutely cannot get past this one, even with the help.  I keep playing with the code, but only get errors.  Here was my latest attempt

ants_mutated <- ants_data_wrangled %>% 
mutate(species=str_replace(species,'^[A-Z][a-z]{0,3}).\.([a-z]{1,4}).", "\1\2"', "Aphatrea"))

**Comment by williamzoughaib** [comment]
Same.  I have been stuck on this for what seems forever.

**Comment by mtaylor-semo** [comment]
This line has a few errors.
```
mutate(species=str_replace(species,'^[A-Z][a-z]{0,3})..([a-z]{1,4}).", "\1\2"', "Aphatrea"))
```
* First, the opening parenthesis is missing so the first pattern cannot be captured. 

* Next, you have two periods in the middle `{0,3})..([a-z]` but those will be treated as any character and not the actual `.` that separates genus and species. You therefore have to escape the second period with two backslashes.

* Next, that same area, the number of characters after the first three is variable, so the first period after the closing parenthesis should be `.*` to find zero or more instances. 

* Next, the last period should also be .* to match zero or more characters after the first four. 

* Next, because you're passing a string, the `\` characters need to be escaped, so `\\1\\2`.

*Next, get rid of `Aphatrea`. Not sure what's going on there.

* Finally (I think) you have combinations of single and double quotes which is confusing the issue. Get rid of the two single quotes, then add an opening double quote at the very start of the string (in front of the missing opening paren).

**Comment by mtaylor-semo** [comment]
This matching sequence has a couple errors.
```
str_replace(species,"([A-Z].{3}).+?\\.([a-z]{1,4})","\\1\\2"))
```
* First, it's best if you use a `^` before [A-Z] to indicate you want to match a capital letter at the start of the string. 

* Next, Amanda did a smart thing by putting `[a-z]{0,3}` after the `[A-Z]` to indicate that 0-3 lower case letters might appear after the first upper case letter. You should do that too.

* `.+?` is contradictory or at least confusing `.+` means 1 or more matches. `.?` means zero or 1 match. I'm honestly not sure R would interpret `.+?` What you want is zero or more matches, so `.*` is the way to go.  

You all are getting close.

**Comment by aerussom** [comment]
ants_mutated <- ants_data_wrangled %>% 
mutate(species=str_replace(species,"((^[A-Z][a-z]{0,3}).*\\.([a-z]{1,4}).*)", "//1//2"))

This code names all my species "//1//2"   :/

How do I replace with the correct names?

**Comment by mtaylor-semo** [comment]
You switched to slashes instead of backslashes for replacement part. Should be `\\1` etc. Also, it looks like you have a `|` for escaping the period between the genus and species names. You again need two backslashes `\\.`.

**Comment by aerussom** [comment]
Caught it, but not before you replied! Thanks!

**Comment by mtaylor-semo** [comment]
I'm living online right now as the questions are coming fast and furious.

**Comment by Andrearashay** [comment]
ants_mutated <- ants_tidy %>% 
  mutate(species = str_replace(species, "((^[A-Z][a-z]{0,3}).\\.([a-z]{1,4}).)", "\\1\\2"))

This is what I have and none of my names have changed.

**Comment by mtaylor-semo** [comment]
Works fine (for me) if you change all `\` to `\\`. The single `\` is an escape character so to use `\` in strings (like searching and matching strings, you need to escape it. Therefore `\\`.

**Comment by Andrearashay** [comment]
That's how it is in my notebook, but when i copied it over it only showed a single '\'.

**Comment by mtaylor-semo** [comment]
I need to see the *exact* code you're running to be able to troubleshoot it. If you're pasting your code into here, use backticks to show your code.  To show your code, type three backticks ( ``` ) on a line, press return, paste or type your code, then do three more backticks on the next line.

**Comment by Andrearashay** [comment]
```
ants_mutated <- ants_tidy %>% 
  mutate(species = str_replace(species, "((^[A-Z][a-z]{0,3}).\\.([a-z]{1,4}).)", "\\1\\2"))
```

**Comment by mtaylor-semo** [comment]
Try adding an asterisk `*` after the first and last `.` in your search strings.  For example, `^[A-Z][a-z]{0,3}).` matches exactly one character after the {0,3} matches. Using `.*` matches zero to thousands of additional characters before the the period that separates the genus and species names.

**Comment by Andrearashay** [comment]
like this?
```
ants_mutated <- ants_tidy %>% 
  mutate(species = str_replace(species, "((^[A-Z][a-z]{0,3}).*\\.([a-z]{1,4}).*)", "\\1\\2"))
```
This changed the names but not as they should be, it added the first 4 letters to the end of the whole name.

**Comment by mtaylor-semo** [comment]
Almost, but you have too many parentheses, which is creating a weird substitution pattern. Get rid of the very first paren, and the last one before the comma.

**Comment by Andrearashay** [comment]
Got it!
