### ISSUE TITLE
creating syndrome_group legend

### ISSUE THREAD

**Issue by aerussom** [SEMO-GABD/public_discussion#25]
phlox_data %>% 
  mutate(syndrome = str_replace(syndrome, "(^be.*e$)", "\\1s"),
         syndrome = str_replace(syndrome, ".+l.?es", "other insects")) %>% 
         mutate(syndrome_group=case_when(syndrome=="autogamous"~"Autogamous",
                                         syndrome=="bat"~"Mammal",
                                         syndrome=="hummingbird"~"Bird",
                                         TRUE~"Insect")) %>% 
  ggplot() +
  geom_point(mapping = aes(x=mean_cor_length, y = mean_throat_width, color = syndrome))

This will not create the syndrome_group column.  It runs without error, but does not change my graph.  I even tried to mutate the data first and then graph, but again, no change.

**Comment by aerussom** [comment]
Got it!

**Comment by mtaylor-semo** [comment]
Your code was close and creative. 
```
phlox_data %>%
mutate(syndrome = str_replace(syndrome, "(^be.*e$)", "\1s"),
syndrome = str_replace(syndrome, ".+l.?es", "other insects")) 
```

First issue is that you're using `syndrome` in `str_replace()` but you don't yet have a `syndrome` column. Replace that with `primary pollinator`, which is the name of your column. (You should avoid using column names with spaces.) Finally, use `\\1s` with two backslashes.  For the second statement, put it in a separate call to `mutate`.

```
phlox_data %>%
  mutate(syndrome = str_replace(`primary pollinator`, "(^be.*e$)", "\\1s")) 
```
