### ISSUE TITLE
HW 14 Part 4

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#27]
This code gives this error:

## Fiji
```{r}
fiji <- getNOAA.bathy(lon1 = min_long,
                      lon2 = max_long,
                      lat1 = min_lat,
                      lat2 = max_lat,
                      antimeridian = TRUE,
                      keep = TRUE)
```
Error in if  (ncol(x) == 3 & !exists("bathy",  inherits = FALSE)) { : argument is of length zero

**Comment by mtaylor-semo** [comment]
Your code ran fine on my computer. Did you install both `raster` and `rgdal` packages? Check `Tools > Check for Package Updates...`. Scroll the list to see if updates are available for either of those packages or for `mar_map.`

**Comment by mtaylor-semo** [comment]
I'm reading through [this thread](https://github.com/ericpante/marmap/issues/10) that discusses the issue.

**Comment by aerussom** [comment]
Same issue. There isn't a "mar_map" for me.   Installing "rgdal" was not in the instructions, however, I installed and attempted to run the code again.  After several minutes, this is still showing in my console....

Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Building bathy matrix ...

**Comment by mtaylor-semo** [comment]
Sorry, you don't need `rgdal`, and `mar_map` should have been `marmap`.

**Comment by mtaylor-semo** [comment]
Did it run after the query?  Querying the NOAA database and building the matrix usually takes less than a minute from my computer.

**Comment by RyanDMcAnulty** [comment]
Code and errors.  I didn't get this far until I loaded "rgdal", and it was the only package from this exercise that had an update available.

## Fiji
```{r}
fiji <- getNOAA.bathy(lon1 = min_long,
                      lon2 = max_long,
                      lat1 = min_lat,
                      lat2 = max_lat,
                      antimeridian = TRUE,
                      keep = TRUE)
```
File already exists  ; loading  'marmap_coord_-170;-42;164;-8_res_4_anti.csv'
##
```{r}
# Could also just use autoplot() without the .bathy extension.
autoplot.bathy(fiji,
               geom =c("raster", "contour"),
               size = 0.1,
               na.rm = TRUE)
```
Error: cannot allocate vector of size 5764256.8 Gb
THAT'S ALOT OF BYTES!!

**Comment by aerussom** [comment]
It never loaded. I closed the message and was able to proceed with my plots,after like Ryan stated, I install and updated 'rgdal'.

**Comment by mtaylor-semo** [comment]
Try [downloading this file](https://github.com/SEMO-GABD/semo-gabd.github.io/raw/master/assignments/hw14/marmap_data.zip) and unzipping it. Put these two files in the same folder as your hw14.Rmd file. Do not put them in your data folder. Then run the code.

**Comment by afreenalam** [comment]
I get a warning- "	
Raster pixels are placed at uneven horizontal intervals and will be shifted. Consider using geom_tile() instead.".
But the plot is formed.

**Comment by mtaylor-semo** [comment]
Then you're OK. (I assume you're talking about part 4).


Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by afreenalam** [comment]
The width to height ratio of plot seems a bit off. Do I have to manually set it?

**Comment by RyanDMcAnulty** [comment]
I Unzipped the two files, put them in my hw14 folder and  get the exact same errors.

**Comment by mtaylor-semo** [comment]
Afreen, I wouldn't worry about it. Some of that is a function of your window spacing. It would automatically change if you adjusted your windows, saved the output, etc.

**Comment by mtaylor-semo** [comment]
Ryan and Amanda, please run `memory.limit()` in the console and let me know what it says. The problem seems to be Windows specific.

**Comment by afreenalam** [comment]
Thank you!

**Comment by RyanDMcAnulty** [comment]
Darn, Bill Gates.

[1] 8094

**Comment by mtaylor-semo** [comment]
I blame Gates for much that is wrong in the computing world. :)  

Please run `memory.limit(24000)` from the console, then try again.

**Comment by RyanDMcAnulty** [comment]
Nope,
I even did memory.limit(240000)

Same thing.

**Comment by RyanDMcAnulty** [comment]
So, for the future...I'm hearing Linux.

**Comment by mtaylor-semo** [comment]
Linux or Mac (both of which are UNIX at the core).

**Comment by mtaylor-semo** [comment]
SKIP part 4!  If you have been following along at home, you have noticed some of the problems with part 4 of the assignment. There are apparent memory allocation issues between PCs, Macs, and Linux that are not worth trouble-shooting right now.  Too bad as it makes some cool maps but it's not worth my time right now to resolve. 

**I will give everyone the full points for this part of the assignment.**

If you are using a Mac or linux, you can complete the assignment. To me, this was the best part of the assignment but I like the ocean!

**Comment by RyanDMcAnulty** [comment]
Darn.
Yeah, it looked really cool.
Will do.

**Comment by RyanDMcAnulty** [comment]
Next big purchase, will be a Mac.

**Comment by mtaylor-semo** [comment]
Actually, try one thing: Run `memory.limit(24000)` *in your code chunk* just before running the the `autoplot.bathy()`. What happens in Notebooks is separate sometimes.

**Comment by RyanDMcAnulty** [comment]
Nope.  Same error.

**Comment by mtaylor-semo** [comment]
I figured but never hurts to try.  At least, it didn't hurt me. Hope you're OK too.

**Comment by RyanDMcAnulty** [comment]
A little singed, but I'll recover.  I have Whoopie Goldberg eyebrows now, though.

**Comment by williamzoughaib** [comment]
I got it to work.  
memory.limit(24000) was included in the 
```{r}
memory.limit(24000)
fiji <- getNOAA.bathy(lon1=min_long,
                      lon2=max_long,
                      lat1=min_lat,
                      lat2=max_lat,
                      antimeridian=TRUE,
                      keep=TRUE)
```

**Comment by williamzoughaib** [comment]
Raster pixels are placed at uneven horizontal intervals and will be shifted. Consider using geom_tile() instead.  I have this as a ggplot warning though

**Comment by mtaylor-semo** [comment]
Cool! Ignore the raster pixels warning.

I would be grateful if other Windows users would try running William's example above and report here.

**Comment by RyanDMcAnulty** [comment]
Still a no go for me.
