### ISSUE TITLE
Plot 5

### ISSUE THREAD

**Issue by williamzoughaib** [SEMO-GABD/public_discussion#29]
CoVid_death_rate <- covid_deaths %>% left_join(covid_positive) %>% 
  group_by(State) %>% 
  summarise(Total_Deaths=sum(deaths,na.rm=TRUE),
            Total_Cases=sum(cases,na.rm=TRUE)) %>% 
  mutate(`Death rate %`=`Total_Deaths`/`Total_Cases`*100)
view(CoVid_death_rate)
CoVid_Table <- CoVid_death_rate %>% 
                     filter(`Death rate %` >= 5) %>% 
                     arrange(desc(`Death rate %`))
CoVid_Table
  This is the code I ran for the table.  But the numbers vastly outweigh your table.  

Are we to filter the date to something in May or June?  As of right now, the dates filtered start with the first US_case.

**Comment by mtaylor-semo** [comment]
Remember that the data are *cumulative.*

**Comment by williamzoughaib** [comment]
I tried this then.  

CoVid_death_rate <- covid_deaths %>% left_join(covid_positive) %>% 
  filter(date==mdy("July 31,2020")) %>% 
  group_by(State) %>% 
  summarise(`Total Deaths`=sum(deaths,na.rm=TRUE),
            `Total Cases`=sum(cases,na.rm=TRUE),.groups='drop') %>% 
  mutate(`Death rate (%)`=`Total Deaths`/`Total Cases`*100)
view(CoVid_death_rate)
CoVid_Table <- CoVid_death_rate %>% 
                     filter(`Death rate %` >= 5) %>% 
                     arrange(desc(`Death rate %`))
CoVid_Table

July 31 would have the final deaths and cases number.  It still is not matching the table.

**Comment by williamzoughaib** [comment]
I have even been googling the CoVid numbers (deaths and positives) for each state and the numbers are fairly close to each other.  Of course these numbers are seven days later than the July 31 cutoff I set.  

https://www.google.com/search?sxsrf=ALeKk01jB3CwejWuQN2Lt13L7XAciWTL2A%3A1596825351876&ei=B58tX7KRNYbGsAXF4oXIDg&q=cases+in+new+york+covid&oq=cases+in+new+york+covid&gs_lcp=CgZwc3ktYWIQAzICCAAyBggAEBYQHjIGCAAQFhAeOgQIABBHOgQIIxAnOgcIABCxAxBDOgUIABCxAzoKCAAQsQMQgwEQQzoKCAAQsQMQFBCHAjoICAAQsQMQgwE6BwgAEBQQhwI6BQgAEMQCOgQIABAKUPqlDFjjtwxgorkMaABwAXgAgAGKAYgBkQySAQQ0LjEwmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwjysPf-3YnrAhUGI6wKHUVxAekQ4dUDCAw&uact=5


Here New York has had 32,329, your table shows only 7247.

**Comment by mtaylor-semo** [comment]
You're missing the meaning of **cumulative.** Let's say we have a 30-day month. We accumulate one new case per day. Day 1 has 1 case, day 2 has 2 cases total, day 3 has 3 cases total. How many total cases have accumulated by the 30th day of the month? It's not 1 + 2 + 3 + 4....etc, which is what your code is doing.
