### ISSUE TITLE
Errorbar placement in hw06

### ISSUE THREAD

**Issue by Andre5569** [SEMO-GABD/public_discussion#5]
![000033](https://user-images.githubusercontent.com/45884213/50701437-6cf61380-1013-11e9-9103-2b76e69ad7d2.png)

In plot 2 of the feathers example, I am able to get the error bars to appear by entering the following.

basal_cort_mean  <-  mean(feathers2$basal_cort, na.rm = TRUE)
basal_cort_sde  <-  sd(feathers2$basal_cort, na.rm =TRUE)/sqrt(33)
basal_min <- basal_cort_mean - basal_cort_sde
basal_max <- basal_cort_mean + basal_cort_sde

ggplot(data=feathers2, mapping = aes(x=site, y=basal_cort))+
  geom_point()+
  geom_errorbar(ymin = basal_min,
                ymax = basal_max)

The problem I have is, the error bars appear the same size and spot on each of the four locations because they are the mean of all the sites. Something tells me that they should actually be the mean of each individual site and should have different position and length.  I trying to think up how this can be done.

**Comment by mtaylor-semo** [comment]
Sounds like your thought process is correct. Did you group by site before calculating the standard error? You can summarize this as part of a pipe. This is my code:

```
feather_sum <- feather %>%
  group_by(site) %>%
  summarize(n = n(),
            mean_basal = mean(basal_cort, na.rm = TRUE),
            se_basal = sd(basal_cort, na.rm = TRUE)/sqrt(n),
            mean_stress = mean(stress_cort, na.rm = TRUE),
            se_stress = sd(stress_cort, na.rm = TRUE)/sqrt(n))
```

This will automatically calulate *n* for each site.
