### ISSUE TITLE
Count function in Assignment 2-3

### ISSUE THREAD

**Issue by dwklingeman** [SEMO-GABD/public_discussion#6]
I was working through Part 3 of Assignment 2 and I've been running into an issue at the tail end of it in section 7. The assignment says to use a "count()" function and whenever I try to use the function I get an error message of: "could not find function 'count'".  What is the proper way to use this function?

![Count function](https://user-images.githubusercontent.com/67530674/86417753-a56fbf80-bc93-11ea-99c2-27c66142a583.PNG)
![count function error](https://user-images.githubusercontent.com/67530674/86417756-a86ab000-bc93-11ea-82c7-7be406bb17b2.PNG)

**Comment by mtaylor-semo** [comment]
Oops! The `count()` function doesn't exist in base R. Skip that step. I had removed it from the **Instructions** section but I didn't get it removed from the code block. I've updated the assignment to remove it.

**Comment by mtaylor-semo** [comment]
Reopening for students to see while assignment is still open.
