### ISSUE TITLE
Running Exercise 3.6.6 lower right graph code chunk

### ISSUE THREAD

**Issue by williamzoughaib** [SEMO-GABD/public_discussion#7]
I am having issues matching my plot to the pictured plot in the book. I used shape=21, stroke=2, and size=3.

ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy,color=drv),shape=21,stroke=2,size=3)
This is what code chunk I ran. I would appreciate some help with this, thanks. I did the other 5 graphs without any issues.

**Comment by mtaylor-semo** [comment]
Take a close read of section 3.3, especially just before the 3.3.1 exercises. You are correctly using shape 21.

**Comment by williamzoughaib** [comment]
Is this the correct code chunk then?  We had not used the fill function yet so I am not sure.
```{r}
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy,fill=drv),shape=21,stroke=2,size=3,color="white")
```

Messing around with the fill function, i did this...and had the colored circles followed by a black outline.  So i added and changed color to white.  Is there a simpler way?
```{r}
ggplot(data=mpg)+
  geom_point(mapping=aes(x=displ,y=hwy,fill=drv),shape=21,stroke=2,size=3)
```

**Comment by mtaylor-semo** [comment]
The default color for stroke (border) is black, so you have to do what you did to override the default. When I make scatterplots that require a fill, I use a stroke of about 0.2-0.25 with the default black. To me, that sets the points off nicely but lets the fill color dominate. Here, however, the goal is to reproduce the figures to help you understand what the different options do. `ggplot2` has lots of options but with that comes a lot of power and flexibility to make outstanding, publication-quality figures. 

Type `?geom_point` in the console then scroll down to the examples. One of the examples shows how to use `color` and `fill`. You can also enter `example(geom_point)` in the console to run the examples shown in the help.
