### ISSUE TITLE
Section 5.3 Question 4

### ISSUE THREAD

**Issue by RyanDMcAnulty** [SEMO-GABD/public_discussion#8]
Dr. Taylor.

**4:** Which flights travelled the longest? Which travelled the shortest?

By traveled the longest, do you mean by time or distance?

Same question for shortest.

Thanks

**Comment by mtaylor-semo** [comment]
Distance.


Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by RyanDMcAnulty** [comment]
Thank you!
